　成功しているのに例外吐くので、調べたらリモートがtomcat5.0の環境だった。http://d.hatena.ne.jp/Ochotona/20060713/1152756149 を参考にtomcat5.5に差し替えたところ、たしかに直った。
